# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bosco}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Wilson"]
  s.date = %q{2010-02-14}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{thing2@jackhq.com}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "Rakefile",
     "VERSION",
     "example/Gemfile",
     "example/app.rb",
     "example/bosco.db",
     "example/config.ru",
     "example/database.rb",
     "example/db/migrate/001_create_results.rb",
     "example/db/migrate/002_create_result_items.rb",
     "example/form.json",
     "example/lib/bosco_mixin.rb",
     "example/views/index.haml",
     "example/views/layout.haml",
     "lib/bosco.rb",
     "lib/bosco/base.rb",
     "lib/bosco/button.rb",
     "lib/bosco/checkboxes.rb",
     "lib/bosco/form.rb",
     "lib/bosco/grid.rb",
     "lib/bosco/list.rb",
     "lib/bosco/multiple_choice.rb",
     "lib/bosco/output.rb",
     "lib/bosco/page.rb",
     "lib/bosco/paragraph.rb",
     "lib/bosco/resources/button.haml",
     "lib/bosco/resources/checkboxes.haml",
     "lib/bosco/resources/form.haml",
     "lib/bosco/resources/grid.haml",
     "lib/bosco/resources/list.haml",
     "lib/bosco/resources/multiple_choice.haml",
     "lib/bosco/resources/page.haml",
     "lib/bosco/resources/paragraph.haml",
     "lib/bosco/resources/scale.haml",
     "lib/bosco/resources/section.haml",
     "lib/bosco/resources/text.haml",
     "lib/bosco/scale.rb",
     "lib/bosco/section.rb",
     "lib/bosco/text.rb",
     "lib/string_to_keys.rb",
     "readme.md",
     "spec/bosco/base_spec.rb",
     "spec/bosco/checkboxes_spec.rb",
     "spec/bosco/form_spec.rb",
     "spec/bosco/grid_spec.rb",
     "spec/bosco/list_spec.rb",
     "spec/bosco/multiple_choice_spec.rb",
     "spec/bosco/output_spec.rb",
     "spec/bosco/page_spec.rb",
     "spec/bosco/paragraph_spec.rb",
     "spec/bosco/scale_spec.rb",
     "spec/bosco/section_spec.rb",
     "spec/bosco/text_spec.rb",
     "spec/bosco_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jackhq/bosco}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/bosco/base_spec.rb",
     "spec/bosco/checkboxes_spec.rb",
     "spec/bosco/form_spec.rb",
     "spec/bosco/grid_spec.rb",
     "spec/bosco/list_spec.rb",
     "spec/bosco/multiple_choice_spec.rb",
     "spec/bosco/output_spec.rb",
     "spec/bosco/page_spec.rb",
     "spec/bosco/paragraph_spec.rb",
     "spec/bosco/scale_spec.rb",
     "spec/bosco/section_spec.rb",
     "spec/bosco/text_spec.rb",
     "spec/bosco_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<haml>, [">= 2.2.17"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<validatable>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<haml>, [">= 2.2.17"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<validatable>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<haml>, [">= 2.2.17"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<validatable>, [">= 0"])
  end
end

